<?php

namespace Ephp\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {

//    public function getIso($geoId) {
//        $q = $em->createQueryBuilder()
//                ->select('iso');
//        $q->where('g.geonameid =:geoId');
//        $q->setParameter('geoId', $geoId);
//        $dql = $q->getQuery();
//        $results = $dql->execute();
//
//        return $results;
//    }

}
