<?php

namespace Ephp\GeoBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * This is the class that validates and merges configuration from your app/config files
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/extension.html#cookbook-bundles-extension-config-class}
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('ephp_geo');

        $rootNode
                ->children()
                    ->arrayNode('map')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('name')->defaultValue('map')->cannotBeEmpty()->end()
                            ->scalarNode('async')->defaultValue(false)->cannotBeEmpty()->end()
                            ->scalarNode('center')->defaultValue(array(41.87194, 12.56738))->cannotBeEmpty()->end()
                            ->scalarNode('language')->defaultValue('it')->cannotBeEmpty()->end()
                            ->scalarNode('width')->defaultValue('100%')->cannotBeEmpty()->end()
                            ->scalarNode('height')->defaultValue('100%')->cannotBeEmpty()->end()
                            ->scalarNode('backgroundColor')->defaultNull()->end()
                            ->scalarNode('disableDefaultUI')->defaultNull()->end()
                            ->scalarNode('draggable')->defaultNull()->end()
                            ->scalarNode('draggableCursor')->defaultNull()->end()
                            ->scalarNode('draggingCursor')->defaultNull()->end()
                            ->scalarNode('heading')->defaultNull()->end()
                            ->scalarNode('keyboardShortcuts')->defaultNull()->end()
                            ->scalarNode('mapMaker')->defaultNull()->end()
                            ->arrayNode('mapTypeControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::RIGHT_TOP)->cannotBeEmpty()->end()
                                    ->scalarNode('style')->defaultValue(\Ivory\GoogleMap\Controls\MapTypeControlStyle::DEFAULT_)->cannotBeEmpty()->end()
                                    ->scalarNode('types')->defaultValue(array(\Ivory\GoogleMap\MapTypeId::ROADMAP, \Ivory\GoogleMap\MapTypeId::SATELLITE, \Ivory\GoogleMap\MapTypeId::TERRAIN, \Ivory\GoogleMap\MapTypeId::HYBRID))->cannotBeEmpty()->end()
                                    ->scalarNode('id')->defaultValue(\Ivory\GoogleMap\MapTypeId::ROADMAP)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->scalarNode('noClear')->defaultNull()->end()
                            ->arrayNode('overviewMapControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('open')->defaultValue(false)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('panControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::LEFT_TOP)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('rotateControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::LEFT_TOP)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('scaleControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::LEFT_TOP)->cannotBeEmpty()->end()
                                    ->scalarNode('style')->defaultValue(\Ivory\GoogleMap\Controls\ScaleControlStyle::DEFAULT_)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->arrayNode('streetViewControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::LEFT_TOP)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                            ->scalarNode('styles')->defaultNull()->end()
                            ->scalarNode('tilt')->defaultNull()->end()
                            ->arrayNode('zoomControl')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('enable')->defaultValue(true)->cannotBeEmpty()->end()
                                    ->scalarNode('position')->defaultValue(\Ivory\GoogleMap\Controls\ControlPosition::LEFT_TOP)->cannotBeEmpty()->end()
                                    ->scalarNode('style')->defaultValue(\Ivory\GoogleMap\Controls\ZoomControlStyle::LARGE)->cannotBeEmpty()->end()
                                    ->scalarNode('auto')->defaultValue(true)->cannotBeEmpty()->end()
                                    ->scalarNode('disableDoubleClickZoom')->defaultNull()->end()
                                    ->scalarNode('min')->defaultNull()->end()
                                    ->scalarNode('max')->defaultNull()->end()
                                    ->scalarNode('scrollwheel')->defaultValue(false)->cannotBeEmpty()->end()
                                    ->scalarNode('zoom')->defaultValue(5)->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                    ->arrayNode('marker')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('name')->defaultValue('marker')->cannotBeEmpty()->end()
                            ->scalarNode('animation')->defaultNull()->end()
                            ->scalarNode('clickable')->defaultNull()->end()
                            ->scalarNode('cursor')->defaultNull()->end()
                            ->scalarNode('draggable')->defaultNull()->end()
                            ->scalarNode('flat')->defaultNull()->end()
                            ->scalarNode('icon')->defaultNull()->end()
                            ->scalarNode('optimized')->defaultNull()->end()
                            ->scalarNode('position')->defaultValue(array(41.87194, 12.56738))->cannotBeEmpty()->end()
                            ->scalarNode('raiseOnDrag')->defaultNull()->end()
                            ->scalarNode('crossOnDrag')->defaultNull()->end()
                            ->scalarNode('shadow')->defaultNull()->end()
                            ->scalarNode('shape')->defaultNull()->end()
                            ->scalarNode('title')->defaultNull()->end()
                            ->scalarNode('visible')->defaultValue(true)->cannotBeEmpty()->end()
                            ->scalarNode('zIndex')->defaultNull()->end()
                        ->end()
                    ->end()
                    ->arrayNode('circle')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('name')->defaultValue('circle')->cannotBeEmpty()->end()
                            ->scalarNode('center')->defaultValue(array(41.87194, 12.56738))->cannotBeEmpty()->end()
                            ->scalarNode('clickable')->defaultNull()->end()
                            ->scalarNode('draggable')->defaultNull()->end()
                            ->scalarNode('editable')->defaultNull()->end()
                            ->scalarNode('fillColor')->defaultNull()->end()
                            ->scalarNode('fillOpacity')->defaultNull()->end()
                            ->scalarNode('radius')->defaultNull()->end()
                            ->scalarNode('strokeColor')->defaultNull()->end()
                            ->scalarNode('strokeOpacity')->defaultNull()->end()
                            ->scalarNode('strokePosition')->defaultNull()->end()
                            ->scalarNode('strokeWeight')->defaultNull()->end()
                            ->scalarNode('visible')->defaultValue(true)->cannotBeEmpty()->end()
                            ->scalarNode('zIndex')->defaultNull()->end()
                        ->end()
                    ->end()
                ->end()
        ;


        return $treeBuilder;
    }
}
